server:
  port: \${PORT:8081}

spring:
  application:
    name: ${rootProject.name}
  datasource:
    url: jdbc:\${DATABASE_JDBC_URI:postgresql://192.168.0.2:5432/\${spring.application.name}db}
    username: \${DATABASE_USER:gsl}
    password: \${DATABASE_PASS:gsl}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    jdbc:
      lob:
        non_contextual_creation: true
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        size-parameter: size
        prefix: ''
        one-indexed-parameters: true
        page-parameter: page
        default-page-size: 20
        qualifier-delimiter: _
        max-page-size: 2000

security:
  ignored=/**:

management:
  endpoints:
    web:
      exposure:
        include: "health"
      base-path: "/"